name: ConnectionPlayerSeparator
version: ${project.version}
main: net.azisaba.connectionplayerseparator.ConnectionPlayerSeparator
description: Bungeeに接続しようとしているプレイヤーの転送先をConfigに指定されたサーバーからランダムに選ぶPluginです
commands:
  cps:
    usage:  /cps
    description: ConnectionPlayerSeparatorの様々な設定ができる

permissions:
  cps.player:
    default: true
  cps.op:
    default: op
  cps.*:
    children:
      cps.op: true
      cps.player: true

